---
os: linux
dist: focal

language: python

python:
  - 3.8
  - 3.7

install: pip install .
before_script: pip install pytest pytest-cov codecov
script: pytest -v --cov=./qintervals
after_success: codecov

jobs:
  include:
    - name: Lint
      install:
      before_script: pip install flake8
      script: flake8
